### ISSUE TITLE
作者你好，LBJPagingMediaBrowser 先放大到垂直方向超过屏幕，再左右滑动，MagnificationGesture会循环卡死

### ISSUE THREAD

**Issue by BugMonkey** [Lebron1992/LBJMediaBrowser#8]
设备 iOS 15.3
LBJViewZoomer 的 zoomGesture 方法

**Comment by Lebron1992** [comment]
谢谢你的反馈。其实我知道这个问题存在，以为还没人用，暂时还没去修复 😂。我尽快看看！

**Comment by Lebron1992** [comment]
https://github.com/Lebron1992/LBJImagePreviewer/commit/4b51499331fbedd1dc0c2f908a16b7f7151483e8

模拟器没问题，真机有问题。已暂时修复这个问题。
